version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_install:
      #Git index should ignore the files that Read the Docs has modified.
      - git update-index --assume-unchanged environment.yml docs/conf.py
      #External links are still valid and readers aren’t linked to non-existent pages.
      - python -m sphinx -b linkcheck -D linkcheck_timeout=1 docs/ $READTHEDOCS_OUTPUT/linkcheck

python:
  install:
    - requirements: docs/requirements.txt
    # Install our python package before building the docs
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

  
formats:
  - pdf
  - epub
